networks:
  webapi-cluster:
    driver: overlay
    attachable: true

x-deploy: &deploy
  endpoint_mode: vip
  resources:
    limits:
      cpus: '0.5'
      memory: 256M
    reservations:
      cpus: '0.25'
      memory: 128M
  update_config:
    parallelism: 1
    order: start-first
    failure_action: rollback
    delay: 10s
  rollback_config:
    parallelism: 0
    order: stop-first
  restart_policy:
    condition: any
    delay: 5s
    max_attempts: 3
    window: 120s

services:
  minio1:
    deploy:
      <<: *deploy
    networks:
      - webapi-cluster

  minio2:
    deploy:
      <<: *deploy
#      placement:
#        constraints:
#          - node.labels.worker.replica == worker-01
    networks:
      - webapi-cluster

  minio3:
    deploy:
      <<: *deploy
#      placement:
#        constraints:
#          - node.labels.worker.replica == worker-02
    networks:
      - webapi-cluster

  minio4:
    deploy:
      <<: *deploy
#      placement:
#        constraints:
#          - node.labels.worker.replica == worker-03
    networks:
      - webapi-cluster

  create-buckets:
    networks:
      - webapi-cluster

