networks:
  mongo:
    driver: overlay
    attachable: true

services:
  mongo-1:
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.labels.worker.replica == worker-01

  mongo-2:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
#      placement:
#        constraints:
#          - node.labels.worker.replica == worker-02

  mongo-3:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
#      placement:
#        constraints:
#          - node.labels.worker.replica == worker-03

    # Add this service to your existing docker-compose.yml
  mongo-express:
    deploy:
      restart_policy:
        condition: on-failure

  mongo-init:
    deploy:
      restart_policy:
        condition: none
