networks:
  mongo:
    driver: overlay
    attachable: true

services:
  mdb-01:
    image: mongo:7.0.5
    networks:
      - mongo
    volumes:
      - /data/mdb-01:/data/db
    command: mongod --replSet datars --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    ports:
      - "27217:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.worker.replica == worker-01

  mdb-02:
    image: mongo:7.0.5
    networks:
      - mongo
    volumes:
      - /data/mdb-02:/data/db
    command: mongod --replSet datars --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.worker.replica == worker-02

  mdb-03:
    image: mongo:7.0.5
    networks:
      - mongo
    volumes:
      - /data/mdb-03:/data/db
    command: mongod --replSet datars --dbpath /data/db --bind_ip 0.0.0.0 --port 27017 --noauth
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.worker.replica == worker-03

  mongo-init:
    image: mongo:7.0.5
    depends_on:
      - mdb-01
      - mdb-02
      - mdb-03
    volumes:
      - ./files/assets/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./files/assets/mongo/init.sh:/init.sh:ro
    entrypoint: ["/bin/bash", "/init.sh"]
    networks:
      - mongo
    deploy:
      restart_policy:
        condition: none
